apiVersion: v1
kind: Service
metadata:
  labels:
    app: spring-boot-so1
  name: spring-boot-so1
spec:
  ports:
  - port: 8086
    protocol: TCP
    targetPort: 8086
  selector:
    app: spring-boot-so1
  type: ClusterIP
