apiVersion: v1
kind: Service
metadata:
  labels:
    app: mysql-standalone
  name: mysql-standalone
spec:
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: mysql-standalone
  type: ClusterIP
